M48
; DRILL file {KiCad (6.0.5)} date Tue Jun 14 13:50:20 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-14T13:50:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.0437Y-4.7008
X5.2713Y-4.7008
X5.5402Y-4.7008
X5.7678Y-4.7008
T0
M30
